# Generated by Django 4.2.3 on 2023-08-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_user_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
